name: Regression End-to-end Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
         name: Mochawesome HTML Report
         path: cypress/reports/html

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
           SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
           SLACK_ICON: https://github.com/rtCamp.png?size=48
           SLACK_MESSAGE: 'Cypress Test Automation Report https://github.com/georgie-liao/Cypress_Test_Automation/actions/runs/${{github.run_id}}'
           SLACK_TITLE: Post Title
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}