name: Parallel Test Build
on: push
jobs:
  Order-Test-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test:registerTest
      
      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome HTML Report - Register Test
          path: cypress/reports/html


  Register-Test-run:
    runs-on: ubuntu-22.04
    steps:
     - name: Checkout
       uses: actions/checkout@v4
        # Install npm dependencies, cache them correctly
        # and run all Cypress tests
     - name: Cypress run
       uses: cypress-io/github-action@v6
       with:
           command: npm run test:placeOrderTest

     - name: Cypress Test Report
       if: always()
       uses: actions/upload-artifact@v3
       with:
        name: Mochawesome HTML Report - Place Order Test
        path: cypress/reports/html
